nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
    # this allows XMLHttRequest from origin http://localhost:3000
        "^/api":
            allow_origin: ["http://localhost:3000"]
            allow_headers: ["*"]
            allow_methods: ["POST", "PUT", "GET", "DELETE"]
            max_age: 3600
